name: Verify

on:
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:

jobs:
  build:
    name: Build
    uses: jetty/.github/.github/workflows/maven-ci.yml@main
    with:
      jdk-matrix: '[ "11", "17", "21" ]'